const ActionName = {
  LOADING: "LOADING",
  LOGIN: "LOGIN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  SIGNUP: "SIGNUP",
  PROFILECOMPLETE:"PROFILECOMPLETE",
  PROFILESELECTOR: "PROFILESELECTOR",
  SKILLS:"SKILLS"
};

export default ActionName;
